### ISSUE TITLE
Investigate how to maintain a changelog

### ISSUE THREAD

**Issue by lo1tuma** [lxanders/mongobird#17]
After our first we release (#16) we should maintain a changelog.

This issue is about how we could achieve this. We can manually edit the changelog or we can create it automatically.

If we want to automatically create the changelog we need to figure out how to do this.
Some possible solutions would be:

* Use all commit messages since the last release.  
This requires a strict commit message policy.
* Use the titles of closed issues except of `wontfix` or `invalid` labeled issues.

- - - - -

The list of changes should be added to a `CHANGELOG.md` and in the git tag description for each release.

**Comment by lxanders** [comment]
@lo1tuma created an initial version of our tool that will be used for managing the changelogs. It is currently not published but [can be found here](https://github.com/lo1tuma/pr-log/).

Next steps for us:

* Extend the `README.md` of `pr-log`
* Publish `pr-log`
* Integrate it into `mongobird`
    * Add it to the `devDependencies`
    * Add a script that runs the tool for a specified version

**Comment by lo1tuma** [comment]
pr-log v.1.0.0 is published
